jbtrivial: Add missing #include <linux/module.h>
drivers/gpio/jbtrivial.c:273:15: error: expected declaration specifiers or ‘...’ before string constant
drivers/gpio/jbtrivial.c:273:1: warning: data definition has no type or storage class
drivers/gpio/jbtrivial.c:273:1: warning: type defaults to ‘int’ in declaration of ‘MODULE_AUTHOR’
drivers/gpio/jbtrivial.c:273:15: warning: function declaration isn’t a prototype
drivers/gpio/jbtrivial.c:274:20: error: expected declaration specifiers or ‘...’ before string constant
drivers/gpio/jbtrivial.c:274:1: warning: data definition has no type or storage class
drivers/gpio/jbtrivial.c:274:1: warning: type defaults to ‘int’ in declaration of ‘MODULE_DESCRIPTION’
drivers/gpio/jbtrivial.c:274:20: warning: function declaration isn’t a prototype
drivers/gpio/jbtrivial.c:275:16: error: expected declaration specifiers or ‘...’ before string constant
drivers/gpio/jbtrivial.c:275:1: warning: data definition has no type or storage class
drivers/gpio/jbtrivial.c:275:1: warning: type defaults to ‘int’ in declaration of ‘MODULE_LICENSE’
drivers/gpio/jbtrivial.c:275:16: warning: function declaration isn’t a prototype

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>